# -*- coding: utf-8 -*-
"""Flipkart BrandName Laptop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GqC0aPV002eXeukmod0s2GTjITE0ry8u
"""

#MODULE

def flipkartA():
  brand=input(str("Enter laptop brand: "))
  url = "https://www.flipkart.com/search?q="+brand+"%20laptops&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
  import pandas as pd
  pd.set_option("display.max_colwidth",None)

  import requests
  from bs4 import BeautifulSoup
  requests.get(url)
  data = requests.get(url)
  soup = BeautifulSoup(data.content)

  #Laptop Name and PRICE
  NAME=[]
  PRICE=[]
  x=0
  while x < len(soup.find_all("div",class_="_4rR01T")):
    for i in soup.find_all("div",class_="_4rR01T")[x]:
      NAME.append(i.split("-")[0])
    for price in soup.find_all("div",class_="_30jeq3 _1_WHN1")[x]:
      PRICE.append(price)
      
    x+=1

  #RAM DRIVE
  RAM=[]
  DRIVE=[]
  x=0
  while x < len(soup.find_all("li",class_="rgWa7D")):
    a=soup.find_all("li",class_="rgWa7D")[x].text
    if "DDR" in a:
      RAM.append(a)
    elif "SSD" in a:
      DRIVE.append(a)
    elif "HDD" in a:
      DRIVE.append(a)
    else:
      pass
    x+=1

  DF=pd.DataFrame(NAME,columns=["Laptop"])
  DF["RAM"]=RAM
  DF["STORAGE"]=DRIVE
  DF["PRICE"]=PRICE
  
  return DF